Repository FIFA22-UT-REC/fifa22-ultimate-team-recommender, pull requests merged in 2022-05, with the labels that each got.

#37 refactor R function to other repo
  Dockerfile
  Makefile
  README.Rmd
  README.md
  docs/README.Rmd
  docs/README.md
  src/R/process_data.R
  src/save_dat.R
Labels: enhancement, help wanted

#42 add Author
  README.md
Labels: documentation

#45 Updating feat-scraper to follow main
  README.md
Labels: documentation, enhancement

#43 developing deep scrap script under notebooks/mock.ipynb
  .github/workflows/publish_docker_image.yml
  .gitignore
  CONTRIBUTING.md
  README.Rmd
  README.md
  data/processed/CAM.csv
  data/processed/CB.csv
  data/processed/CDM.csv
  data/processed/CF.csv
  data/processed/CM.csv
  data/processed/GK.csv
  data/processed/LB.csv
  data/processed/LM.csv
  data/processed/LW.csv
  data/processed/LWB.csv
  data/processed/RB.csv
  data/processed/RM.csv
  data/processed/RW.csv
  data/processed/RWB.csv
  data/processed/ST.csv
  data/raw/player_raw_data.csv
  data/raw/player_raw_data_old_version.csv
  data/raw/player_raw_data_v1.csv
  docs/README.Rmd
  docs/README.md
  logs/logs.log
  main.py
  notebooks/mock.ipynb
  notebooks/web_scraped.ipynb
  scraper/extract_info.py
  scraper/scraper.py
  scraper/scraper_utlis.py
  scraper/stats_utils/__init__.py
  scraper/stats_utils/extract_att.py
  scraper/stats_utils/extract_deep.py
  scraper/stats_utils/extract_def.py
  scraper/stats_utils/extract_goalkeep.py
  scraper/stats_utils/extract_mentality.py
  scraper/stats_utils/extract_move.py
  scraper/stats_utils/extract_pow.py
  scraper/stats_utils/extract_skill.py
  scraper/stats_utils/extract_stats.py
  scraper/stats_utils/test_extract_att.py
  scraper/stats_utils/test_extract_deep.py
  scraper/stats_utils/test_extract_def.py
  scraper/stats_utils/test_extract_goalkeep.py
  scraper/stats_utils/test_extract_mentality.py
  scraper/stats_utils/test_extract_move.py
  scraper/stats_utils/test_extract_pow.py
  scraper/stats_utils/test_extract_skill.py
  scraper/stats_utils/test_extract_stats.py
  utils/flatten.py
  utils/multi_threading.py
  utils/pipeline.py
  utils/save_csv.py
Labels: bug, enhancement, help wanted

#47 added new notebook to perform KMeans clustering
  logs/logs.log
  notebooks/data_prep.ipynb
  scraper/stats_utils/test_extract_skill.py
  scraper/stats_utils/tests/__init__.py
  scraper/stats_utils/tests/test_extract_att.py
  scraper/stats_utils/tests/test_extract_deep.py
  scraper/stats_utils/tests/test_extract_def.py
  scraper/stats_utils/tests/test_extract_goalkeep.py
  scraper/stats_utils/tests/test_extract_mentality.py
  scraper/stats_utils/tests/test_extract_move.py
  scraper/stats_utils/tests/test_extract_pow.py
  scraper/stats_utils/tests/test_extract_skill.py
  scraper/stats_utils/tests/test_extract_stats.py
Labels: enhancement, help wanted
